import { access, mkdir, writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'

export const gardenMetaRootName = '_meta'
export const gardenFrontmatterReferenceFilename = 'frontmatter.md'
export const gardenFrontmatterReferenceRelativePath = `${gardenMetaRootName}/${gardenFrontmatterReferenceFilename}`

const pathExists = async (ref: string): Promise<boolean> =>
  access(ref).then(
    () => true,
    () => false,
  )

export const buildGardenFrontmatterReferenceSource = (): string => `# Garden Page Frontmatter

This file is generated by Wonderlands. It stays private under \`${gardenMetaRootName}/\` so agents and editors can inspect the current Garden page schema without publishing this reference.

## Minimal Example

\`\`\`yaml
---
title: Example Page
description: One-line summary shown under the title and used as the default meta description.
date: 2026-04-05
---
\`\`\`

## Full Example

\`\`\`yaml
---
title: Example Page
description: One-line summary shown under the title and used as the default meta description.
excerpt: Short summary used in generated listings.
tags: [tools, bash]
cover_image: /public/covers/example.jpg
order: 10
date: 2026-04-05
updated: 2026-04-06
draft: false
publish: true
listing: false
listing_page_size: 12
template: default
visibility: public
seo_title: Example Page
seo_description: Example summary for search.
seo_canonical: https://example.com/page
seo_keywords: [tools, bash]
seo_noindex: false
seo_image: /public/covers/example.jpg
---
\`\`\`

## Supported Fields

- \`title\`: page title. Falls back to a titleized slug when omitted.
- \`description\`: shown under the page title and used as the default meta description.
- \`excerpt\`: used in generated listings. Falls back to \`description\` when omitted.
- \`tags\`: array or comma-separated string.
- \`cover_image\`: path to a file under \`public/**\`.
- \`order\`: ascending sibling order in sidebar and generated listings.
- \`date\`: planted date.
- \`updated\`: tended date.
- \`draft: true\`: excludes the page from output.
- \`publish: false\`: excludes the page from output.
- \`listing: true\`: turns the page into a generated listing of child pages.
- \`listing_page_size\`: overrides the site default listing size. Must be positive.
- \`template\`: reserved for future template variants.
- \`visibility\`: \`public\`, \`protected\`, or \`private\`.
- \`seo_title\`
- \`seo_description\`
- \`seo_canonical\`
- \`seo_keywords\`
- \`seo_noindex\`
- \`seo_image\`: accepted in metadata today, but not yet surfaced by the renderer.

## Rules

- Put publishable assets under \`public/**\`.
- In markdown and \`cover_image\`, reference publishable assets as \`public/...\` or \`/public/...\`, not guessed final site URLs.
- \`visibility: protected\` only works for pages included by \`_garden.yml\` \`public.roots\`.
- \`visibility: private\` emits no route at all.
- \`${gardenMetaRootName}/\`, \`attachments/\`, and \`system/\` are private helper roots and are never published.
`

export interface GardenMetaEnsureResult {
  createdPaths: string[]
  skippedPaths: string[]
}

export const ensureGardenSourceMetaFiles = async (
  sourceScopeRef: string,
): Promise<GardenMetaEnsureResult> => {
  const createdPaths: string[] = []
  const skippedPaths: string[] = []
  const metaRootRef = resolve(sourceScopeRef, gardenMetaRootName)
  const frontmatterReferenceRef = resolve(sourceScopeRef, gardenFrontmatterReferenceRelativePath)

  if (await pathExists(metaRootRef)) {
    skippedPaths.push(`${gardenMetaRootName}/`)
  } else {
    await mkdir(metaRootRef, { recursive: true })
    createdPaths.push(`${gardenMetaRootName}/`)
  }

  if (await pathExists(frontmatterReferenceRef)) {
    skippedPaths.push(gardenFrontmatterReferenceRelativePath)
  } else {
    await writeFile(frontmatterReferenceRef, buildGardenFrontmatterReferenceSource(), 'utf8')
    createdPaths.push(gardenFrontmatterReferenceRelativePath)
  }

  return {
    createdPaths,
    skippedPaths,
  }
}
